plugins:
  - jekyll-feed
title: "Red's Blog"
description: "Red's Blog - tech, gaming, linux, foss and more!"
author: RedSQL
url: https://redsql.github.io
permalink: /blog/entries/:title:output_ext

# Conversion
markdown:    kramdown
highlighter: rouge

# defaults
def_title: "Red's Pile"
def_description: "Where all my stuff goes to rot..."

# feed settings
feed:
    excerpt_only: true

# chraset fix attempt
encoding: UTF-8
